import 'package:flutter/material.dart';

class HighlightsInner extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      child: Column(
        children: <Widget>[
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
          Text('HighlightsInner'),
        ],
      ),
    );
  }
}
