import 'package:flutter/material.dart';

final ThemeData darkTheme = ThemeData(
    accentColor: Color(0xfffb6b4c),
    accentColorBrightness: Brightness.dark,
    backgroundColor: Color(0xff464646),
    bottomAppBarColor: Color(0xff424242),
    brightness: Brightness.dark,
    buttonColor: Color(0xff1e88e5),
    canvasColor: Color(0xff161616),
    cardColor: Color(0xff232323),
    cursorColor: Color(0xff4285f4),
    dialogBackgroundColor: Color(0xff424242),
    disabledColor: Color(0x62ffffff),
    dividerColor: Color(0x1fffffff),
    errorColor: Color(0xffEF5D60),
    highlightColor: Color(0x40cccccc),
    hintColor: Color(0x80ffffff),
    hoverColor: Color(0xfffb6b4c),
    indicatorColor: Color(0xff64ffda),
    primaryColor: Color(0xffFFFFFF),
    primaryColorBrightness: Brightness.dark,
    primaryColorDark: Color(0xff000000),
    primaryColorLight: Color(0xff9e9e9e),
    scaffoldBackgroundColor: Color(0xff161616),
    secondaryHeaderColor: Color(0xff616161),
    selectedRowColor: Color(0xfff5f5f5),
    splashColor: Color(0x40cccccc),
    textSelectionColor: Color(0xff64ffda),
    textSelectionHandleColor: Color(0xff1de9b6),
    toggleableActiveColor: Color(0xff64ffda),
    unselectedWidgetColor: Color(0xb3ffffff),
    visualDensity: VisualDensity.adaptivePlatformDensity,
    textTheme: ThemeData.dark().textTheme.copyWith(
          headline1: TextStyle(color: Color(0xffffffff)),
          headline2: TextStyle(color: Color(0xffffffff)),
          headline3: TextStyle(color: Color(0xffffffff)),
          headline4: TextStyle(color: Color(0xffffffff)),
          headline5: TextStyle(color: Color(0xffffffff)),
          headline6: TextStyle(color: Color(0xffffffff)),
          subtitle1: TextStyle(color: Color(0xffffffff)),
          subtitle2: TextStyle(color: Color(0xffffffff)),
          caption: TextStyle(color: Color(0xffffffff)),
          bodyText1: TextStyle(color: Color(0xffffffff)),
          bodyText2: TextStyle(color: Color(0xffffffff)),
        ));
