import 'package:flutter/material.dart';

final ThemeData lightTheme = ThemeData(
    accentColor: Color(0xfffb6b4c),
    accentColorBrightness: Brightness.light,
    backgroundColor: Color(0xfff0f0f0),
    bottomAppBarColor: Color(0xffffffff),
    brightness: Brightness.light,
    buttonColor: Color(0xffe0e0e0),
    canvasColor: Color(0xfffafafa),
    cardColor: Color(0xffffffff),
    cursorColor: Color(0xff4285f4),
    dialogBackgroundColor: Color(0xffffffff),
    disabledColor: Color(0x61000000),
    dividerColor: Color(0x1f000000),
    errorColor: Color(0xffEF5D60),
    highlightColor: Color(0x66bcbcbc),
    hintColor: Color(0x8a000000),
    hoverColor: Color(0xfffb6b4c),
    indicatorColor: Color(0xff2196f3),
    primaryColor: Color(0xff440044),
    primaryColorBrightness: Brightness.light,
    primaryColorDark: Color(0xff1976d2),
    primaryColorLight: Color(0xffbbdefb),
    scaffoldBackgroundColor: Color(0xfffcfcfc),
    secondaryHeaderColor: Color(0xffe3f2fd),
    selectedRowColor: Color(0xfff5f5f5),
    splashColor: Color(0x66c8c8c8),
    textSelectionColor: Color(0xff90caf9),
    textSelectionHandleColor: Color(0xff64b5f6),
    toggleableActiveColor: Color(0xff1e88e5),
    unselectedWidgetColor: Color(0x8a000000),
    visualDensity: VisualDensity.adaptivePlatformDensity,
    textTheme: ThemeData.dark().textTheme.copyWith(
          headline1: TextStyle(color: Color(0xff440044)),
          headline2: TextStyle(color: Color(0xff440044)),
          headline3: TextStyle(color: Color(0xff440044)),
          headline4: TextStyle(color: Color(0xff440044)),
          headline5: TextStyle(color: Color(0xff440044)),
          headline6: TextStyle(color: Color(0xff440044)),
          subtitle1: TextStyle(color: Color(0xff440044)),
          subtitle2: TextStyle(color: Color(0xff440044)),
          caption: TextStyle(color: Color(0xff440044)),
          bodyText1: TextStyle(color: Color(0xff440044)),
          bodyText2: TextStyle(color: Color(0xff440044)),
        ));
